/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package premièreint_graphi_blanc;

/**
 *
 * @author User
 */
public class Fenêtre_principale extends javax.swing.JFrame {

    /**
     * Creates new form Fenêtre_principale
     */
    public Fenêtre_principale() {
        initComponents();
        System.out.println("fenêtre creer");
        mvgbienvenue.setText("Bonjour Le Monde");
        mvgresultat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mvgbienvenue = new javax.swing.JLabel();
        mvgAurevoir = new javax.swing.JLabel();
        Bouton_validé = new javax.swing.JButton();
        Zonenom = new javax.swing.JTextField();
        mvgdemandeprenom = new javax.swing.JLabel();
        mvgresultat = new javax.swing.JLabel();
        Salaire = new javax.swing.JLabel();
        Zonesalaire = new javax.swing.JTextField();
        Augemnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mvgbienvenue.setText("Maxime Blanc");

        mvgAurevoir.setText("Good bye");

        Bouton_validé.setText("Change all");
        Bouton_validé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_validéActionPerformed(evt);
            }
        });

        Zonenom.setText(" ");
        Zonenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZonenomActionPerformed(evt);
            }
        });

        mvgdemandeprenom.setText("Entrer votre Prenom");

        mvgresultat.setText("Résultat");

        Salaire.setText("Entrer votre salaire");

        Zonesalaire.setText(" ");

        Augemnter.setText("Augmenter le salaire");
        Augemnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AugemnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mvgdemandeprenom)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(mvgAurevoir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bouton_validé)
                                    .addComponent(mvgbienvenue)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(mvgresultat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Salaire)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Zonesalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Augemnter)
                    .addComponent(Zonenom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(mvgbienvenue)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zonenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mvgdemandeprenom))
                .addGap(26, 26, 26)
                .addComponent(Bouton_validé)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(mvgresultat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salaire)
                    .addComponent(Zonesalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Augemnter))
                .addGap(6, 6, 6)
                .addComponent(mvgAurevoir)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_validéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_validéActionPerformed
        mvgAurevoir.setText("Au revoir en francais");
        
        String a= Zonenom.getText();
        mvgresultat.setText("Bonjour"+a);
        
        mvgresultat.setVisible(true);
    }//GEN-LAST:event_Bouton_validéActionPerformed

    private void ZonenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZonenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZonenomActionPerformed

    private void AugemnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AugemnterActionPerformed
        String salaire = Zonesalaire.getText();
        int salaire_entier = Integer.parseInt(salaire);
        salaire_entier++;
        Zonesalaire.setText(salaire_entier+"");
    }//GEN-LAST:event_AugemnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenêtre_principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Augemnter;
    private javax.swing.JButton Bouton_validé;
    private javax.swing.JLabel Salaire;
    private javax.swing.JTextField Zonenom;
    private javax.swing.JTextField Zonesalaire;
    private javax.swing.JLabel mvgAurevoir;
    private javax.swing.JLabel mvgbienvenue;
    private javax.swing.JLabel mvgdemandeprenom;
    private javax.swing.JLabel mvgresultat;
    // End of variables declaration//GEN-END:variables
}
